### ISSUE TITLE
Error init project

### ISSUE THREAD

**Issue by ilyar** [bem-incubator/bem-tools-init#1]
``` bash
$  npm -v && node -v
2.14.9
v0.12.9
$ npm i -g bem/bem-tools#WIP
$ npm i -g bem-incubator/bem-tools-init
$ bem init my-test-project
fs.js:761
  return binding.readdir(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/space/lab/bem/test/node_modules'
    at Error (native)
    at Object.fs.readdirSync (fs.js:761:18)
    at npmls (/home/ilyar/.nvm/versions/node/v0.12.9/lib/node_modules/bem/node_modules/npmls/index.js:61:23)
    at Object.<anonymous> (/home/ilyar/.nvm/versions/node/v0.12.9/lib/node_modules/bem/index.js:22:39)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by tadatuta** [comment]
@ilyar Thank you, fixed in https://github.com/bem/bem-tools/commit/9224c43f820dffc5b00f5eb6878e9ff048a9c50a

**Comment by ilyar** [comment]
Thank you :+1:
